### ISSUE TITLE
Token parameter is not a valid token in userInfo

### ISSUE THREAD

**Issue by vitomanu96** [IBM-Security/verify-sdk-javascript#38]
I'am using the verify-sdk-javascript with React.

My configuration is:

       tenantUrl: 'https://xxxxxxxx.ice.ibmcloud.com',
       clientId: 'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx',
       redirectUri: 'http://localhost:3000/authorize/callback',
       scope: 'openid profile',
       flowType: 'implicit',
       responseType: 'id_token token',
       storageType: localStorage

Code spinnet:

      if (window.location.pathname === '/authorize/callback') {
            
         this.oauthClient.handleCallback().catch(e => console.error('ERROR IN handleCallback', e))
            const token = this.oauthClient.fetchToken()
           console.log('TOKEN ', token) // the token is printed correctly in console 
           if (!token || !token.access_token) {
                console.error('NO TOKEN')
            }

            this.oauthClient.userInfo(token).then(user => {
                console.log('USER INFO:', user)
            }).catch(e => console.error('error in user info', e))

            window.location.replace('/')
         }

Error stack after calling **ouathClient.userInfo(token)** :

Token Error: Token parameter is not a valid token
    at b.userInfo (http://localhost:3000/static/js/0.chunk.js:19716:51)
    at App.render (http://localhost:3000/static/js/main.chunk.js:103:24)
    at finishClassComponent (http://localhost:3000/static/js/0.chunk.js:40958:24)
    at updateClassComponent (http://localhost:3000/static/js/0.chunk.js:40905:28)
    at beginWork (http://localhost:3000/static/js/0.chunk.js:42490:20)
    at beginWork$1 (http://localhost:3000/static/js/0.chunk.js:47282:18)
    at performUnitOfWork (http://localhost:3000/static/js/0.chunk.js:46142:16)
    at workLoopSync (http://localhost:3000/static/js/0.chunk.js:46079:9)
    at renderRootSync (http://localhost:3000/static/js/0.chunk.js:46045:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/0.chunk.js:45662:22)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/0.chunk.js:45250:11)
    at updateContainer (http://localhost:3000/static/js/0.chunk.js:48787:7)
    at http://localhost:3000/static/js/0.chunk.js:49319:11
    at unbatchedUpdates (http://localhost:3000/static/js/0.chunk.js:45802:16)
    at legacyRenderSubtreeIntoContainer (http://localhost:3000/static/js/0.chunk.js:49318:9)
    at Object.render (http://localhost:3000/static/js/0.chunk.js:49401:14)
    at Module.<anonymous> (http://localhost:3000/static/js/main.chunk.js:322:50)
    at Module../src/index.js (http://localhost:3000/static/js/main.chunk.js:411:30)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:857:31)
    at fn (http://localhost:3000/static/js/bundle.js:151:20)
    at Object.1 (http://localhost:3000/static/js/main.chunk.js:673:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:857:31)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:101

A strange thing is that on the local storage there is just an empty object saved as token:

![chromedev](https://user-images.githubusercontent.com/16103224/105367437-b9afe580-5c00-11eb-9d9a-e141281f1f09.png)

It is like the library is not saving the token on localStorage (already tried with sessionStorage).

**Comment by trumanbutter** [comment]
@vitomanu96 just to confirm are you using the react sample that gets generated from the developer portal application? or are you using your own custom react app?

If you are using your own custom react app you're most likely missing an additional config property which usually gets generated for that config.

Try adding `REDIRECT_URI_ROUTE: '/authorize/callback'`  to your config and let me know if that fixes your problem.

**Comment by trumanbutter** [comment]
Closing out stale issue.
